# Generated by Django 4.2 on 2023-04-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_descriptoin_projects_caption_projects_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='name',
        ),
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
