# Generated by Django 4.2 on 2023-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_projects_name_alter_projects_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
