# Generated by Django 4.2 on 2023-04-17 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_projects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
